[elastic]
uri=""
skipTLS=true
username=""
password=""
questionsMetadataIndex=""
sessionIndex=""

[server]
port=8083

[videostore]
uri="https://github.com/SaiprasadKrishnamurthy/sample_video_files/raw/master/%s.mp4"
workDir="./videos"

[nats]
url="nats://127.0.0.1:4222"
interviewCompletedSubject="interviewCompleted"

[transcoding]
timeoutInSeconds=5
