[elastic]
uri=""
skipTLS=true
username=""
password=""
questionsMetadataIndex=""
sessionIndex=""
questionResultIndex=""

[server]
port=8083

[videostore]
uri="https://github.com/SaiprasadKrishnamurthy/sample_video_files/raw/master/%s.mp4"
workDir="./videos"

[nats]
url="nats://127.0.0.1:4222"
interviewCompletedSubject="interviewCompleted"
transcodingCompletedSubject="transcodingCompleted"
transcriptionCompletedSubject="transcriptionCompleted"

[transcoding]
timeoutInSeconds=5

[transcription]
googleApplicationCredentials="google_transcription.json"
language="en-IN"
sampleRateHertz=16000
timeoutInSeconds=30
